/**
 * Country dialling codes for the sign-in form, so a number can be entered the
 * way people actually write it locally instead of in E.164 by hand.
 *
 * `trunk` marks countries that use a national trunk prefix (usually 0) which is
 * dropped when the number is written internationally: 07911 123456 in the UK is
 * +44 7911 123456. Italy is the well-known exception - its landline numbers keep
 * the leading 0 - so it is deliberately not marked.
 */

const COUNTRIES = [
	{ name: "Albania", iso: "AL", dial: "355", trunk: true },
	{ name: "Algeria", iso: "DZ", dial: "213", trunk: true },
	{ name: "Argentina", iso: "AR", dial: "54", trunk: true },
	{ name: "Armenia", iso: "AM", dial: "374", trunk: true },
	{ name: "Australia", iso: "AU", dial: "61", trunk: true },
	{ name: "Austria", iso: "AT", dial: "43", trunk: true },
	{ name: "Azerbaijan", iso: "AZ", dial: "994", trunk: true },
	{ name: "Bahrain", iso: "BH", dial: "973" },
	{ name: "Bangladesh", iso: "BD", dial: "880", trunk: true },
	{ name: "Belarus", iso: "BY", dial: "375", trunk: true },
	{ name: "Belgium", iso: "BE", dial: "32", trunk: true },
	{ name: "Bolivia", iso: "BO", dial: "591" },
	{ name: "Bosnia and Herzegovina", iso: "BA", dial: "387", trunk: true },
	{ name: "Brazil", iso: "BR", dial: "55", trunk: true },
	{ name: "Bulgaria", iso: "BG", dial: "359", trunk: true },
	{ name: "Cambodia", iso: "KH", dial: "855", trunk: true },
	{ name: "Cameroon", iso: "CM", dial: "237" },
	{ name: "Canada", iso: "CA", dial: "1", nsn: 10 },
	{ name: "Chile", iso: "CL", dial: "56" },
	{ name: "China", iso: "CN", dial: "86", trunk: true },
	{ name: "Colombia", iso: "CO", dial: "57" },
	{ name: "Costa Rica", iso: "CR", dial: "506" },
	{ name: "Croatia", iso: "HR", dial: "385", trunk: true },
	{ name: "Cuba", iso: "CU", dial: "53" },
	{ name: "Cyprus", iso: "CY", dial: "357" },
	{ name: "Czechia", iso: "CZ", dial: "420" },
	{ name: "Denmark", iso: "DK", dial: "45" },
	{ name: "Dominican Republic", iso: "DO", dial: "1", nsn: 10 },
	{ name: "Ecuador", iso: "EC", dial: "593", trunk: true },
	{ name: "Egypt", iso: "EG", dial: "20", trunk: true },
	{ name: "El Salvador", iso: "SV", dial: "503" },
	{ name: "Estonia", iso: "EE", dial: "372" },
	{ name: "Ethiopia", iso: "ET", dial: "251", trunk: true },
	{ name: "Finland", iso: "FI", dial: "358", trunk: true },
	{ name: "France", iso: "FR", dial: "33", trunk: true },
	{ name: "Georgia", iso: "GE", dial: "995", trunk: true },
	{ name: "Germany", iso: "DE", dial: "49", trunk: true },
	{ name: "Ghana", iso: "GH", dial: "233", trunk: true },
	{ name: "Greece", iso: "GR", dial: "30" },
	{ name: "Guatemala", iso: "GT", dial: "502" },
	{ name: "Honduras", iso: "HN", dial: "504" },
	{ name: "Hong Kong", iso: "HK", dial: "852" },
	{ name: "Hungary", iso: "HU", dial: "36", trunk: true },
	{ name: "Iceland", iso: "IS", dial: "354" },
	{ name: "India", iso: "IN", dial: "91", trunk: true },
	{ name: "Indonesia", iso: "ID", dial: "62", trunk: true },
	{ name: "Iran", iso: "IR", dial: "98", trunk: true },
	{ name: "Iraq", iso: "IQ", dial: "964", trunk: true },
	{ name: "Ireland", iso: "IE", dial: "353", trunk: true },
	{ name: "Israel", iso: "IL", dial: "972", trunk: true },
	// No trunk flag: Italian landline numbers keep their leading 0.
	{ name: "Italy", iso: "IT", dial: "39" },
	{ name: "Ivory Coast", iso: "CI", dial: "225" },
	{ name: "Jamaica", iso: "JM", dial: "1", nsn: 10 },
	{ name: "Japan", iso: "JP", dial: "81", trunk: true },
	{ name: "Jordan", iso: "JO", dial: "962", trunk: true },
	{ name: "Kazakhstan", iso: "KZ", dial: "7", trunk: true },
	{ name: "Kenya", iso: "KE", dial: "254", trunk: true },
	{ name: "Kuwait", iso: "KW", dial: "965" },
	{ name: "Latvia", iso: "LV", dial: "371" },
	{ name: "Lebanon", iso: "LB", dial: "961", trunk: true },
	{ name: "Libya", iso: "LY", dial: "218", trunk: true },
	{ name: "Lithuania", iso: "LT", dial: "370", trunk: true },
	{ name: "Luxembourg", iso: "LU", dial: "352" },
	{ name: "Macau", iso: "MO", dial: "853" },
	{ name: "Malaysia", iso: "MY", dial: "60", trunk: true },
	{ name: "Malta", iso: "MT", dial: "356" },
	{ name: "Mexico", iso: "MX", dial: "52", trunk: true },
	{ name: "Moldova", iso: "MD", dial: "373", trunk: true },
	{ name: "Montenegro", iso: "ME", dial: "382", trunk: true },
	{ name: "Morocco", iso: "MA", dial: "212", trunk: true },
	{ name: "Myanmar", iso: "MM", dial: "95", trunk: true },
	{ name: "Nepal", iso: "NP", dial: "977", trunk: true },
	{ name: "Netherlands", iso: "NL", dial: "31", trunk: true },
	{ name: "New Zealand", iso: "NZ", dial: "64", trunk: true },
	{ name: "Nicaragua", iso: "NI", dial: "505" },
	{ name: "Nigeria", iso: "NG", dial: "234", trunk: true },
	{ name: "North Macedonia", iso: "MK", dial: "389", trunk: true },
	{ name: "Norway", iso: "NO", dial: "47" },
	{ name: "Oman", iso: "OM", dial: "968" },
	{ name: "Pakistan", iso: "PK", dial: "92", trunk: true },
	{ name: "Panama", iso: "PA", dial: "507" },
	{ name: "Paraguay", iso: "PY", dial: "595", trunk: true },
	{ name: "Peru", iso: "PE", dial: "51", trunk: true },
	{ name: "Philippines", iso: "PH", dial: "63", trunk: true },
	{ name: "Poland", iso: "PL", dial: "48" },
	{ name: "Portugal", iso: "PT", dial: "351" },
	{ name: "Puerto Rico", iso: "PR", dial: "1", nsn: 10 },
	{ name: "Qatar", iso: "QA", dial: "974" },
	{ name: "Romania", iso: "RO", dial: "40", trunk: true },
	{ name: "Russia", iso: "RU", dial: "7", trunk: true },
	{ name: "Saudi Arabia", iso: "SA", dial: "966", trunk: true },
	{ name: "Senegal", iso: "SN", dial: "221" },
	{ name: "Serbia", iso: "RS", dial: "381", trunk: true },
	{ name: "Singapore", iso: "SG", dial: "65" },
	{ name: "Slovakia", iso: "SK", dial: "421", trunk: true },
	{ name: "Slovenia", iso: "SI", dial: "386", trunk: true },
	{ name: "South Africa", iso: "ZA", dial: "27", trunk: true },
	{ name: "South Korea", iso: "KR", dial: "82", trunk: true },
	{ name: "Spain", iso: "ES", dial: "34" },
	{ name: "Sri Lanka", iso: "LK", dial: "94", trunk: true },
	{ name: "Sweden", iso: "SE", dial: "46", trunk: true },
	{ name: "Switzerland", iso: "CH", dial: "41", trunk: true },
	{ name: "Taiwan", iso: "TW", dial: "886", trunk: true },
	{ name: "Tanzania", iso: "TZ", dial: "255", trunk: true },
	{ name: "Thailand", iso: "TH", dial: "66", trunk: true },
	{ name: "Trinidad and Tobago", iso: "TT", dial: "1", nsn: 10 },
	{ name: "Tunisia", iso: "TN", dial: "216" },
	{ name: "Turkey", iso: "TR", dial: "90", trunk: true },
	{ name: "Uganda", iso: "UG", dial: "256", trunk: true },
	{ name: "Ukraine", iso: "UA", dial: "380", trunk: true },
	{ name: "United Arab Emirates", iso: "AE", dial: "971", trunk: true },
	{ name: "United Kingdom", iso: "GB", dial: "44", trunk: true },
	{ name: "United States", iso: "US", dial: "1", nsn: 10 },
	{ name: "Uruguay", iso: "UY", dial: "598", trunk: true },
	{ name: "Uzbekistan", iso: "UZ", dial: "998", trunk: true },
	{ name: "Venezuela", iso: "VE", dial: "58", trunk: true },
	{ name: "Vietnam", iso: "VN", dial: "84", trunk: true },
	{ name: "Zambia", iso: "ZM", dial: "260", trunk: true },
	{ name: "Zimbabwe", iso: "ZW", dial: "263", trunk: true }
];

export const DEFAULT_COUNTRY = "US";

export function findCountry(iso) {
	return COUNTRIES.find(c => c.iso === iso) || COUNTRIES.find(c => c.iso === DEFAULT_COUNTRY);
}

export default COUNTRIES;
